service: ${self:custom.defaults.service}-s3-street-market-pictures
frameworkVersion: ${self:custom.defaults.version}
provider:
  name: aws
  stage: ${self:custom.defaults.stage}
  region: ${self:custom.defaults.region}
  deploymentBucket:
    name: ${self:custom.defaults.service}-${self:provider.region}-${aws:accountId}
    serverSideEncryption: AES256
custom:
  base: ${self:service}-${self:provider.stage}-${self:provider.region}-${aws:accountId}
  defaults: ${file(../../../defaults/cloudgto.yml):defaults}
plugins:
  - serverless-deployment-bucket
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.base}
        PublicAccessBlockConfiguration:
          BlockPublicPolicy: false
          BlockPublicAcls: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
    S3BucketPolicy:
      DependsOn: S3Bucket
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:resources.Resources.S3Bucket.Properties.BucketName}
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:resources.Resources.S3Bucket.Properties.BucketName}/*
  Outputs:
    S3BucketName:
      Description: S3 Bucket Name
      Value: ${self:resources.Resources.S3Bucket.Properties.BucketName}
